### ISSUE TITLE
KeyError: 'patch_embed.proj.weight'

### ISSUE THREAD

**Issue by r-kellerm** [SwinTransformer/Video-Swin-Transformer#22]
**Describe the bug**
When trying to fine-tune a pretrained model, the following error occurs:
`KeyError: 'patch_embed.proj.weight'`
For the line:
`state_dict['patch_embed.proj.weight'] = state_dict['patch_embed.proj.weight'].unsqueeze(2).repeat(1,1,self.patch_size[0],1,1) / self.patch_size[0]`

**Reproduction**

1. What command or script did you run?

```
python3 tools/train.py configs/recognition/swin/swin_small_patch244_window877_kinetics400_1k.py --cfg-options model.backbone.pretrained=pretrained/swin_small_patch244_window877_kinetics400_1k.pth model.backbone.use_checkpoint=True
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
- Only changed the following:
```
--- a/mmaction/models/backbones/swin_transformer.py
+++ b/mmaction/models/backbones/swin_transformer.py
-        state_dict = checkpoint['model']
+       state_dict = checkpoint['state_dict'] #checkpoint['model']

```
3. What dataset did you use?
kinetics-based
**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: linux
Python: 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
CUDA available: True
GPU 0,1,2,3: Quadro RTX 8000
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
PyTorch: 1.9.0+cu102
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PT
HREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-
field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-st
rict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -falig
ned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TO
RCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.10.0+cu102
OpenCV: 4.5.3
MMCV: 1.3.13
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMAction2: 0.15.0+db018fb

**Error traceback**

If applicable, paste the error traceback here.

```
2021-09-12 22:44:38,014 - mmaction - INFO - load model from: pretrained/swin_small_patch244_window877_kinetics400_1k.pth
Traceback (most recent call last):
  File "<venv dir>/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "Video-Swin-Transformer/mmaction/models/recognizers/base.py", line 109, in __init__
    self.init_weights()
  File "Video-Swin-Transformer/mmaction/models/recognizers/base.py", line 126, in init_weights
    self.backbone.init_weights()
  File "Video-Swin-Transformer/mmaction/models/backbones/swin_transformer.py", line 641, in init_weights
    self.inflate_weights(logger)
  File "Video-Swin-Transformer/mmaction/models/backbones/swin_transformer.py", line 588, in inflate_weights
    state_dict['patch_embed.proj.weight'] = state_dict['patch_embed.proj.weight'].unsqueeze(2).repeat(1,1,self.patch_size[0],1,1) / self.patch_size[0]
KeyError: 'patch_embed.proj.weight'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 201, in <module>
    main()
  File "tools/train.py", line 156, in main
    model = build_model(
  File "Video-Swin-Transformer/mmaction/models/builder.py", line 70, in build_model
    return build_localizer(cfg)
  File "Video-Swin-Transformer/mmaction/models/builder.py", line 62, in build_localizer
    return LOCALIZERS.build(cfg)
  File "<venv_dir>/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "<venv dir>/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "<venv dir>/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "Recognizer3D: 'patch_embed.proj.weight'"

```

**Bug fix**

Looks like the pretrained models are compatible with an older version of mmaction - but I couldn't find which.

Thanks!

**Comment by hust-nj** [comment]
Hi, please see this issue https://github.com/SwinTransformer/Video-Swin-Transformer/issues/21, you need to install our project instead of mmaction2 repo.

**Comment by r-kellerm** [comment]
> Hi, please see this issue #21, you need to install our project instead of mmaction2 repo.

Thanks for your response!
uninstalled mmaction2 and reinstalled with `pip install -v -e . `, but still getting the error from `mmcv`:
2021-09-30 13:20:02,304 - mmaction - INFO - load model from: pretrained/swin_small_patch244_window877_kinetics400_1k.pth
Traceback (most recent call last):

>   File "<homedir>/.local/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
>     return obj_cls(**args)
>   File "exp/Video-Swin-Transformer/mmaction/models/recognizers/base.py", line 109, in __init__
>     self.init_weights()
>   File "exp/Video-Swin-Transformer/mmaction/models/recognizers/base.py", line 126, in init_weights
>     self.backbone.init_weights()
>   File "exp/Video-Swin-Transformer/mmaction/models/backbones/swin_transformer.py", line 641, in init_weights
>     self.inflate_weights(logger)
>   File "exp/Video-Swin-Transformer/mmaction/models/backbones/swin_transformer.py", line 588, in inflate_weights
>     state_dict['patch_embed.proj.weight'] = state_dict['patch_embed.proj.weight'].unsqueeze(2).repeat(1,1,self.patch_size[0],1,1) / self.patch_size[0]
> KeyError: 'patch_embed.proj.weight'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "tools/train.py", line 201, in <module>
>     main()
>   File "tools/train.py", line 156, in main
>     model = build_model(
>   File "exp/Video-Swin-Transformer/mmaction/models/builder.py", line 70, in build_model
>     return build_localizer(cfg)
>   File "exp/Video-Swin-Transformer/mmaction/models/builder.py", line 62, in build_localizer
>     return LOCALIZERS.build(cfg)
>   File "<homedir>/.local/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
>     return self.build_func(*args, **kwargs, registry=self)
>   File "<homedir>/.local/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
>     return build_from_cfg(cfg, registry, default_args)
>   File "<homedir>/.local/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
>     raise type(e)(f'{obj_cls.__name__}: {e}')
> KeyError: "Recognizer3D: 'patch_embed.proj.weight'"
> 

Installed `mmcv` through: `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html`.

**Comment by Dzw1219** [comment]
Modified the config file.
Add 'pretrained2d=False'
model=dict(backbone=dict(patch_size=(2,4,4), drop_path_rate=0.1, pretrained2d=False), test_cfg=dict(max_testing_views=4))

**Comment by hayleeXinyi** [comment]
> > Hi, please see this issue #21, you need to install our project instead of mmaction2 repo.
> 
> Thanks for your response! uninstalled mmaction2 and reinstalled with `pip install -v -e . `, but still getting the error from `mmcv`: 2021-09-30 13:20:02,304 - mmaction - INFO - load model from: pretrained/swin_small_patch244_window877_kinetics400_1k.pth Traceback (most recent call last):
> 
> > File "/.local/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
> > return obj_cls(**args)
> > File "exp/Video-Swin-Transformer/mmaction/models/recognizers/base.py", line 109, in **init**
> > self.init_weights()
> > File "exp/Video-Swin-Transformer/mmaction/models/recognizers/base.py", line 126, in init_weights
> > self.backbone.init_weights()
> > File "exp/Video-Swin-Transformer/mmaction/models/backbones/swin_transformer.py", line 641, in init_weights
> > self.inflate_weights(logger)
> > File "exp/Video-Swin-Transformer/mmaction/models/backbones/swin_transformer.py", line 588, in inflate_weights
> > state_dict['patch_embed.proj.weight'] = state_dict['patch_embed.proj.weight'].unsqueeze(2).repeat(1,1,self.patch_size[0],1,1) / self.patch_size[0]
> > KeyError: 'patch_embed.proj.weight'
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "tools/train.py", line 201, in 
> > main()
> > File "tools/train.py", line 156, in main
> > model = build_model(
> > File "exp/Video-Swin-Transformer/mmaction/models/builder.py", line 70, in build_model
> > return build_localizer(cfg)
> > File "exp/Video-Swin-Transformer/mmaction/models/builder.py", line 62, in build_localizer
> > return LOCALIZERS.build(cfg)
> > File "/.local/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
> > return self.build_func(*args, **kwargs, registry=self)
> > File "/.local/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
> > return build_from_cfg(cfg, registry, default_args)
> > File "/.local/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
> > raise type(e)(f'{obj_cls.**name**}: {e}')
> > KeyError: "Recognizer3D: 'patch_embed.proj.weight'"
> 
> Installed `mmcv` through: `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html`.

Hi! Have you solved this problem? Or do you have any other alternative model recommended, I think this model has too many bugs that need to be solved.
