### ISSUE TITLE
    if results['frame_inds'].ndim != 1: KeyError: 'frame_inds'

### ISSUE THREAD

**Issue by Note-Liu** [SwinTransformer/Video-Swin-Transformer#3]
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/envs/pytorch/lib/python3/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/envs/pytorch/lib/python3/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/envs/pytorch/lib/python3/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/Video-Swin-Transformer-master/mmaction/datasets/base.py", line 287, in __getitem__
    return self.prepare_train_frames(idx)
  File "/home/Video-Swin-Transformer-master/mmaction/datasets/rawframe_dataset.py", line 168, in prepare_train_frames
    return self.pipeline(results)
  File "/home/Video-Swin-Transformer-master/mmaction/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/ideo-Swin-Transformer-master/mmaction/datasets/pipelines/loading.py", line 1153, in __call__
    if results['frame_inds'].ndim != 1:
KeyError: 'frame_inds'

**Comment by pandababyer** [comment]
I guess you didn't write the config file correct. You can check the compose order in your train_pipeline: maybe you put the DecordDecode before SampleFrames or you miss it .
![image](https://user-images.githubusercontent.com/24407543/141945569-043e6e0d-b59e-4190-8422-29746900380f.png)
